### ISSUE TITLE
New Versioning Process for 3.0.0+

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#488]
EDIT: we decided to use "-dev" and "-rc" tags instead of "-alpha" and "-beta".

Some small changes to our versioning process will improve our development workflow:

# Previous Process

- Pre-releases
  - Tagged versions: 2.6-beta, 2.6-beta2
  - Untagged versions: 2.6-beta-X, 2.6-beta2-X
    - X = number of commits since last pre-release tag
- Releases
  - Tagged versions: 2.0, 2.6, 2.6.1
-  Post-releases
   - Untagged versions: 2.6-X
     - X = number of commits since last release tag

To support post-release versioning, all release tags were reachable within the “master” branch, but it also blocked new development within “master” until that release was ready (development during beta periods happens in a separate branch).

The new process will replace post-release versioning with pre-release "-dev" versioning and allow for unblocked "master" branch development.

# Proposed Process

The main changes are:

* Change "-beta" tag to "-rc" (people like it better)
* Upon creating the an initial "-rc", we also immediately create the next "-dev" to continue working on:

![Zeek-Versioning-Process](https://user-images.githubusercontent.com/422685/61919550-fe26cc00-af0a-11e9-96b0-470a94a3fbb4.png)

# Tasks

- [x] Modify the “update-changes” script
  - [x] Allow “-rc” and "-dev" pre-release tags (similar to how we did “-beta” already)
  - [x] Pre-release version increments should be like “-rc.1” instead of “-rc-1”
- [x] Teach the “scripts/base/misc/version.zeek” about the “-dev” and "-rc" pre-release tags
- [x] Update Travis rules to automatically test both “release/*” and “master” branches

# Details / Rationale

* For Zeek, there's no more post-release version numbers, everything is a pre-release or a release

* Our versioning within the master branch is now based off an “-dev” pre-release tag using a version number targeted at our next official feature/release.  It’s created as soon as a “-rc” tag is also created and we resume the usual development process in the “master” branch without having to wait for the beta period to resolve into a final release.

* The “-dev” tag is somewhat arbitrarily named, but we need to pick something and happens to lexically sort how we’d want it to: 3.1.0-dev.1 < 3.1.0-rc < 3.1.0-rc.1 < 3.1.0-rc2 < 3.1.0-rc2.1 < 3.1.0 < 3.1.1

* Always use full X.Y.Z for tags (don't abbreviate X.Y.0 into X.Y).  The advantage is that a lot of tooling built for strict SemVer expect it (we are not strict SemVer in terms of what minor releases mean, but our goals for providing some sense of ordering are similar enough).

* Pre-release increment identifiers should use a ‘.’ instead of a ‘-’.  E.g. 3.1.0-dev.1, not 3.1.0-dev-1.  Again, advantage is that SemVer and tooling meant to work for it interpret pre-release identifier components lexically unless it contains only numbers (then it’s compared numerically).  E.g. 3.1.0-dev-2 > 3.1.0-dev-10, but 3.1.0-dev.2 < 3.1.0-dev.10.

* Using pre-release versions for a patch release is optional.  If used, it needs to follow the same "-dev" or “-rc” process, else it’s fine to go straight from 3.0.0 to 3.0.1.

* Sub-projects (e.g. zeekctl, broker, etc.) may still use the old post-release versioning scheme if they choose to.  They do not have a planned release cycle and the semantics of either pre-release or post-release are the same anyway: there’s *no* compatibility guarantees whatsoever (it’s not an “official” release).  Pre-release and post-release versions are only provided as a convenient ordering mechanism -- they help answer vague questions regarding "newness", but do not necessarily specify or imply relationship to what's contained in the the official release numbers.
