### ISSUE TITLE
3.0.1 meta issue

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#604]
Just collecting a list of things targeted for 3.0.1 so we have a separate reminder to port/merge them to `release/3.0`.  Can of course do that gradually over time as things get finished, just find it easier to track in a central location since they'll likely land in `master` at different times.  The alternative of depending on people to create PRs against `release/3.0` also seems similarly scattered and error-prone, but open to ideas on how to best organize.

- [x] #598: `to_json()` support for `set` with composite keys
- [x] #615: add `print_raw()` BIF as convenience/workaround for #596
- [x] #595: json logging performance regression
- [x] #602: external plugins can't find paraglob header
- [x] #593: sub-microsecond interval descriptions (also needs cde28074a169212aa8f38fdac225ecbeac4e642d)
- [x] bc18ca44e6d18c28c92818fdc11dcd645c33d675: ptr_func Xcode compiler warnings
- [x] zeek/broker#58: broker Xcode compiler warnings
- [x] #591: `set[enum]` options don't work
- [x] #606: ambiguous json format for vectors with null elements
  - not a regression as 2.6.4 did a different thing that was also wrong, but still clearly a bug to fix
- [x] #611: memory leak and "incorrect" field order in RecordVal JSON formatting
- [x] #632: fix `redef` of table to use a different `&default` value
- [x] ~~#621: just the commit that fixes the `tcp_option` event~~
  - "not important enough"
- [x] ~~#596: allow `print` to output utf-8~~
  - Original thought was there's a regression between 2.6.4 and 3.0.0 because the former outputs a valid json format using `print to_json(s)` while the later may now output invalid json.  But changing the default semantics of `print` may be a breaking change in some contexts (e.g. external plugin unit tests), so safer to target 3.1.0 rather than 3.0.1.  Also, technically 2.6.4's version of `print` doesn't generally guarantee valid json formatting of arbitrary string data, so users should not be using it for that purpose in the first place.
- [x] https://github.com/zeek/broker/pull/67: libc++ mismatch between CAF and Broker
- [x] #667: fix signature matching for payload-carrying TCP SYN packets
- [x] #678: fix ZEEK_PROFILER_FILE
- [x] #649: fix OpenBSD build
  - Needs 49c59ce, zeek/cmake@e8ddcae, #679, and CAF 0.16.5
- [x] #685: fix RPC call parsing

**Comment by timwoj** [comment]
> #615: add print_raw() BIF as convenience/workaround for #596

That can be removed since we decided to close that PR, right?

**Comment by jsiwek** [comment]
I'll plan to do the 3.0.1 release this week.  Let me know if there's any significant bugs/issues still not addressed that would be good to squeeze in.

The one questionable thing I had was whether to get the larger json changes (switching to rapidjson) from #595 in, but think it's not critical and can wait -- didn't seem to generally be a lot of complaints about the performance regression and also the most significant portion of it will be addressed in 3.0.1 with the switch to the tsl map type.

**Comment by timwoj** [comment]
Robin and I talked about it last week. Go ahead and  release what we have, and we can work on rapidjson or some other fixes for a later release.

**Comment by jsiwek** [comment]
3.0.1 is released: https://github.com/zeek/zeek/releases/tag/v3.0.1

Also, updated and moved over the release process docs from zeek.org to https://docs.zeek.org/en/latest/devel/maintainers/release-process.html
